// One-off build script: converts Natural Earth Sri Lanka geometry into a
// simplified SVG path + shared projection constants for the app.
// Not part of the shipped app; run manually with `node scripts/build-map.mjs`.
import fs from "node:fs";

const geometry = JSON.parse(fs.readFileSync("scripts/srilanka-10m.json", "utf8"));

// geometry.coordinates: array of polygons, each an array of rings, each an array of [lon, lat]
const polygons = geometry.coordinates.map((poly) => poly[0]);

function perpendicularDistance(point, lineStart, lineEnd) {
  const [x, y] = point;
  const [x1, y1] = lineStart;
  const [x2, y2] = lineEnd;
  const dx = x2 - x1;
  const dy = y2 - y1;
  const len = Math.sqrt(dx * dx + dy * dy);
  if (len === 0) return Math.sqrt((x - x1) ** 2 + (y - y1) ** 2);
  const t = ((x - x1) * dx + (y - y1) * dy) / (len * len);
  const projX = x1 + t * dx;
  const projY = y1 + t * dy;
  return Math.sqrt((x - projX) ** 2 + (y - projY) ** 2);
}

function douglasPeucker(points, epsilon) {
  if (points.length < 3) return points;
  let maxDist = 0;
  let index = 0;
  const end = points.length - 1;
  for (let i = 1; i < end; i++) {
    const dist = perpendicularDistance(points[i], points[0], points[end]);
    if (dist > maxDist) {
      maxDist = dist;
      index = i;
    }
  }
  if (maxDist > epsilon) {
    const left = douglasPeucker(points.slice(0, index + 1), epsilon);
    const right = douglasPeucker(points.slice(index), epsilon);
    return left.slice(0, -1).concat(right);
  }
  return [points[0], points[end]];
}

// Simplify the large main-island ring more aggressively than the small islets.
const simplified = polygons.map((ring) =>
  ring.length > 100 ? douglasPeucker(ring, 0.003) : ring
);

simplified.forEach((ring, i) =>
  console.log(`ring ${i}: ${polygons[i].length} -> ${ring.length} points`)
);

// --- projection: equirectangular, longitude corrected by cos(latRef) ---
const allPoints = simplified.flat();
const lats = allPoints.map((p) => p[1]);
const lons = allPoints.map((p) => p[0]);
const latRef = (Math.min(...lats) + Math.max(...lats)) / 2;
const lonRef = (Math.min(...lons) + Math.max(...lons)) / 2;
const cosLatRef = Math.cos((latRef * Math.PI) / 180);

function rawXY([lon, lat]) {
  const x = (lon - lonRef) * cosLatRef;
  const y = latRef - lat;
  return [x, y];
}

const rawPoints = allPoints.map(rawXY);
const rawXs = rawPoints.map((p) => p[0]);
const rawYs = rawPoints.map((p) => p[1]);
const minX = Math.min(...rawXs);
const maxX = Math.max(...rawXs);
const minY = Math.min(...rawYs);
const maxY = Math.max(...rawYs);

const TARGET_HEIGHT = 620; // internal px "budget" for the tallest extent
const PAD = 26;
const scale = TARGET_HEIGHT / (maxY - minY);
const width = (maxX - minX) * scale;
const height = (maxY - minY) * scale;

const translateX = PAD - minX * scale;
const translateY = PAD - minY * scale;
const viewBoxWidth = Math.round(width + PAD * 2);
const viewBoxHeight = Math.round(height + PAD * 2);

function project([lon, lat]) {
  const [rx, ry] = rawXY([lon, lat]);
  return [
    Math.round((rx * scale + translateX) * 100) / 100,
    Math.round((ry * scale + translateY) * 100) / 100,
  ];
}

function ringToPath(ring) {
  const pts = ring.map(project);
  return "M" + pts.map((p) => p.join(",")).join("L") + "Z";
}

// Sort rings by point count descending; the first (biggest) is the main island.
const ringsByArea = simplified
  .map((ring, i) => ({ ring, i, path: ringToPath(ring) }))
  .sort((a, b) => b.ring.length - a.ring.length);

const mainPath = ringsByArea[0].path;
const isletPaths = ringsByArea.slice(1).map((r) => r.path);

const out = `// AUTO-GENERATED by scripts/build-map.mjs — do not hand-edit.
// Source: Natural Earth 10m Admin 0 Countries (Sri Lanka), simplified with
// Douglas-Peucker and projected to an equirectangular view corrected for
// latitude ${latRef.toFixed(3)}.

export const MAP_VIEWBOX_WIDTH = ${viewBoxWidth};
export const MAP_VIEWBOX_HEIGHT = ${viewBoxHeight};

// projection constants shared with src/utils/projection.ts
export const PROJECTION = {
  lonRef: ${lonRef},
  latRef: ${latRef},
  cosLatRef: ${cosLatRef},
  scale: ${scale},
  translateX: ${translateX},
  translateY: ${translateY},
};

export const SRI_LANKA_MAIN_PATH = "${mainPath}";

export const SRI_LANKA_ISLET_PATHS = [
${isletPaths.map((p) => `  "${p}",`).join("\n")}
];
`;

fs.writeFileSync("src/data/srilankaShape.ts", out);
console.log("wrote src/data/srilankaShape.ts");
console.log({ latRef, lonRef, scale, viewBoxWidth, viewBoxHeight });

// --- second, coarser pass for the low-poly 3D diorama ---
// A blunter epsilon than the 2D pass (0.003) gives the faceted, "laser cut
// paper" silhouette the diorama look wants; the 2D map stays crisp/precise.
// Re-uses the exact same project() closure/constants as the 2D pass above
// (not a fresh bounding box from the coarser points) so the 2D and 3D maps
// are always geographically consistent with each other.
const EPSILON_3D = 0.012;
const simplified3d = polygons.map((ring) => (ring.length > 100 ? douglasPeucker(ring, EPSILON_3D) : ring));

simplified3d.forEach((ring, i) => console.log(`3d ring ${i}: ${polygons[i].length} -> ${ring.length} points`));

const WORLD_SCALE = 0.014;

function toWorld([lon, lat]) {
  const [svgX, svgY] = project([lon, lat]);
  return [
    Math.round((svgX - viewBoxWidth / 2) * WORLD_SCALE * 10000) / 10000,
    Math.round((svgY - viewBoxHeight / 2) * WORLD_SCALE * 10000) / 10000,
  ];
}

// Same "biggest ring = main island" convention as the 2D pass.
const ringsByArea3d = simplified3d
  .map((ring) => ({ ring, worldPoints: ring.map(toWorld) }))
  .sort((a, b) => b.ring.length - a.ring.length);

const mainRing3d = ringsByArea3d[0].worldPoints;
const isletRings3d = ringsByArea3d.slice(1).map((r) => r.worldPoints);

function ringLiteral(points, indent) {
  const pad = " ".repeat(indent);
  return `[\n${points.map(([x, z]) => `${pad}  [${x}, ${z}],`).join("\n")}\n${pad}]`;
}

const out3d = `// AUTO-GENERATED by scripts/build-map.mjs — do not hand-edit.
// Same source geometry and projection as src/data/srilankaShape.ts, but with
// a coarser Douglas-Peucker pass (epsilon ${EPSILON_3D}) for a low-poly,
// faceted "paper diorama" silhouette, converted to flat world-space [x, z]
// pairs for the 3D scene: x = (svgX - ${viewBoxWidth}/2) * WORLD_SCALE, z the
// same for svgY. No "three" import here on purpose, so importing this data
// never pulls the three.js bundle along with it.

export const WORLD_SCALE = ${WORLD_SCALE};

export const ISLAND_MAIN_RING: [number, number][] = ${ringLiteral(mainRing3d, 0)};

export const ISLAND_ISLET_RINGS: [number, number][][] = [
${isletRings3d.map((r) => `  ${ringLiteral(r, 2)},`).join("\n")}
];
`;

fs.writeFileSync("src/data/srilankaShape3d.ts", out3d);
console.log("wrote src/data/srilankaShape3d.ts");
console.log({ mainRingPoints: mainRing3d.length, isletRingCounts: isletRings3d.map((r) => r.length) });
